### ISSUE TITLE
Please remove these plugins as "officially supported"

### ISSUE THREAD

**Issue by bitshiftnetau** [truenas/iocage-ix-plugins#16]
With respect, it's clear these plugins receive very little support and that's fine. You can only do so much. 

Please just remove them. The average user is perfectly capable of running up a jail and installing what we need. What we don't need or appreciate is being led down the garden path.

Either remove them or support them, but please choose.

**Comment by william-gr** [comment]
@bitshiftnetau why are you using this repo? Are you a TrueNAS Enterprise customer?

**Comment by bitshiftnetau** [comment]
Nope. Is there another github for the official plugins that I shoud use?

**Comment by william-gr** [comment]
https://github.com/ix-plugin-hub/iocage-plugin-index

**Comment by bitshiftnetau** [comment]
Those are the community plugins. Not the 'official' plugins. See my OP. 

You should remove them if you aren't going to test and support them properly.

**Comment by william-gr** [comment]
https://github.com/freenas/iocage-ix-plugins
